# Generated by Django 3.2.21 on 2023-11-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0001_initial'),
        ('likes', '0002_auto_20231103_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='gaming',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gaming_likes', to='gaming.gaming'),
        ),
    ]
